export const NAV_ITEMS = [
  ["overview", "Passport"],
  ["evidence", "Tune feed"],
  ["agent", "Practice run"],
  ["connected-agent", "Live run"],
  ["constitution", "My mix"],
  ["visas", "Apps"],
  ["migration", "Copy feed"],
  ["temporary", "Incognito"],
  ["companion", "Blend"],
  ["drift", "Check feed"],
  ["continuity", "Creators"],
  ["templates", "Presets"],
  ["history", "Receipts"],
  ["clerk", "Ask Curate"],
];

export const INITIAL_CONSTITUTION = {
  version: 3,
  title: "Alex's portable feed",
  intent:
    "Show me independent games, thoughtful design, local culture, and research. Keep the pace calm, preserve genuine surprise, and never automate public engagement.",
  topics: [
    { id: "independent_games", label: "Independent games", percent: 35, color: "green" },
    { id: "design", label: "Design", percent: 30, color: "blue" },
    { id: "local_culture", label: "Local culture", percent: 20, color: "gold" },
    { id: "research", label: "Research", percent: 15, color: "coral" },
  ],
  serendipity: 20,
  outrageCeiling: 5,
  sourceDiversity: 70,
  creatorCeiling: 15,
  languages: ["English", "German"],
  expiresIn: "7 days",
};

export const DESTINATIONS = [
  {
    id: "lab",
    name: "Curate Lab",
    shortName: "Proof Lab",
    status: "Practice",
    tone: "blue",
    connected: true,
    certification: "Safe local practice",
    actions: ["Preview a sample feed", "Try reversible changes", "Compare the result", "Return to the start"],
    limitation: "A private practice space that shows the full Curate flow without touching a social account.",
  },
  {
    id: "bluesky",
    name: "Bluesky",
    shortName: "Bluesky",
    status: "Guided",
    tone: "purple",
    connected: true,
    certification: "Guided connection ready",
    actions: ["Carry creator choices", "Translate topic preferences", "Guide account controls", "Show what will not transfer"],
    limitation: "Curate stays in guided mode unless a verified test connection is active.",
  },
  {
    id: "x",
    name: "X",
    shortName: "X",
    status: "Guided + Lab",
    tone: "purple",
    connected: false,
    certification: "Documented API + pinned Phoenix source",
    actions: ["Compile documented controls", "Inspect pinned reference source", "Create guided handoffs"],
    limitation: "No Phoenix execution receipt and no claim of reading or controlling the production For You feed.",
  },
  {
    id: "youtube",
    name: "YouTube",
    shortName: "YouTube",
    status: "Guided",
    tone: "purple",
    connected: true,
    certification: "Subscription route ready",
    actions: ["Carry subscriptions", "Translate topic interests", "Guide native feedback"],
    limitation: "Curate can manage supported subscriptions, but YouTube keeps control of the Home feed.",
  },
  {
    id: "reddit",
    name: "Reddit",
    shortName: "Reddit",
    status: "Guided",
    tone: "purple",
    connected: false,
    certification: "Registration pending",
    actions: ["Recommend communities", "Compile mute plan", "Guide native steps"],
    limitation: "API access and account actions require a Reddit-accepted Data API registration.",
  },
  {
    id: "instagram",
    name: "Instagram",
    shortName: "Instagram",
    status: "Guided",
    tone: "orange",
    connected: false,
    certification: "Portability import",
    actions: ["Map followed creators", "Compile native controls", "Verify exported evidence"],
    limitation: "Official portability data and user-driven native controls only.",
  },
  {
    id: "facebook",
    name: "Facebook",
    shortName: "Facebook",
    status: "Guided",
    tone: "purple",
    connected: false,
    certification: "Portability import",
    actions: ["Map follows", "Compile Favorites plan", "Guide native controls"],
    limitation: "No unsupported News Feed mutations are claimed.",
  },
  {
    id: "threads",
    name: "Threads",
    shortName: "Threads",
    status: "Guided",
    tone: "green",
    connected: false,
    certification: "Regional native controls",
    actions: ["Compile Dear Algo prompt", "Preserve intent", "Issue a receipt"],
    limitation: "Native Your Algo flows are used only where available.",
  },
  {
    id: "tiktok",
    name: "TikTok",
    shortName: "TikTok",
    status: "Guided + import",
    tone: "orange",
    connected: false,
    certification: "Eligibility dependent",
    actions: ["Read eligible export", "Compile Refresh plan", "Guide topic controls"],
    limitation: "No unsupported For You feed-control writes.",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    shortName: "LinkedIn",
    status: "Guided + import",
    tone: "blue",
    connected: false,
    certification: "Portability dependent",
    actions: ["Map follows", "Compile unfollow plan", "Guide native controls"],
    limitation: "No unsupported feed-control writes.",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    shortName: "Snapchat",
    status: "Guided",
    tone: "gold",
    connected: false,
    certification: "Native controls only",
    actions: ["Compile content controls", "Guide subscriptions", "Record completion"],
    limitation: "No autonomous recommendation mutation is claimed.",
  },
];

export const TEMPLATES = [
  {
    id: "deep-work",
    name: "Deep Work Week",
    code: "DW-07",
    note: "Research and long-form sources with a strict outrage ceiling.",
    intent: "Prioritize research, thoughtful design, and long-form sources. Keep novelty useful and the pace quiet.",
    topics: [40, 25, 10, 25],
    serendipity: 10,
    outrageCeiling: 2,
    duration: "7 days",
    tone: "blue",
  },
  {
    id: "local-weekend",
    name: "Local Weekend",
    code: "LW-48",
    note: "Places, events, local reporting, and nearby independent creators.",
    intent: "Show me local culture, nearby events, independent places, and useful reporting for this weekend.",
    topics: [15, 15, 55, 15],
    serendipity: 25,
    outrageCeiling: 4,
    duration: "48 hours",
    tone: "green",
  },
  {
    id: "conference",
    name: "Conference Mode",
    code: "CF-72",
    note: "A temporary field briefing around a chosen professional topic.",
    intent: "Build a focused field briefing around the conference, its speakers, and independent commentary.",
    topics: [20, 25, 15, 40],
    serendipity: 20,
    outrageCeiling: 5,
    duration: "72 hours",
    tone: "coral",
  },
  {
    id: "slow-feed",
    name: "Slow Feed",
    code: "SF-30",
    note: "Fewer repeated creators and more source diversity for one month.",
    intent: "Slow the feed down. Prefer diverse sources, fewer repeated creators, and material worth saving.",
    topics: [25, 30, 20, 25],
    serendipity: 18,
    outrageCeiling: 3,
    duration: "30 days",
    tone: "purple",
  },
];

export const CREATOR_FIXTURES = [
  {
    id: "studio-a",
    name: "Studio A",
    field: "Independent games",
    source: "Bluesky",
    destination: "YouTube",
    destinationHandle: "@studio-a",
    confidence: 100,
    evidence: "Reviewed creator directory",
  },
  {
    id: "paper-lab",
    name: "Paper Lab",
    field: "Research",
    source: "Bluesky",
    destination: "YouTube",
    destinationHandle: "@paper-lab",
    confidence: 100,
    evidence: "Reviewed creator directory",
  },
  {
    id: "city-zine",
    name: "City Zine",
    field: "Local culture",
    source: "Instagram",
    destination: "Bluesky",
    destinationHandle: "city-zine.example",
    confidence: 100,
    evidence: "Reviewed creator directory",
  },
  {
    id: "studio-a-x",
    name: "Studio A",
    field: "Independent games",
    source: "Bluesky",
    destination: "X",
    destinationHandle: "studio_a",
    confidence: 100,
    evidence: "Reviewed creator directory",
  },
];

export const INITIAL_RECEIPTS = [
  {
    id: "RCPT-1042",
    type: "Constitution saved",
    detail: "Version 3 became the active portable policy.",
    time: "29 AUG 2026 · 10:05",
    status: "Succeeded",
    reversible: false,
    checkpoint: "v2",
  },
  {
    id: "RCPT-1038",
    type: "Guided migration handoff prepared",
    detail: "Proof Lab to Bluesky; 8 guided steps were prepared and no external account action was claimed.",
    time: "29 AUG 2026 · 09:42",
    status: "Succeeded",
    reversible: false,
    checkpoint: "v2",
  },
  {
    id: "RCPT-1031",
    type: "Temporary visa expired",
    detail: "Local Launch mode closed and its isolated overlay was removed.",
    time: "28 AUG 2026 · 20:00",
    status: "Expired cleanly",
    reversible: false,
    checkpoint: "v2",
  },
  {
    id: "RCPT-1026",
    type: "Creator continuity",
    detail: "Studio A matched from Bluesky to YouTube in the reviewed creator directory.",
    time: "28 AUG 2026 · 16:18",
    status: "Succeeded",
    reversible: false,
    checkpoint: "v1",
  },
];

export const INITIAL_ACTIVITY = [
  {
    id: "ACT-3004",
    actor: "Curate",
    detail: "Checked where the current mix can travel across the selected apps.",
    time: "10:08",
    state: "Verified",
  },
  {
    id: "ACT-3003",
    actor: "You",
    detail: "Stamped version 3 with a five-percent outrage ceiling.",
    time: "10:05",
    state: "Recorded",
  },
  {
    id: "ACT-3002",
    actor: "Curate",
    detail: "Kept YouTube Home out because that control is not available.",
    time: "10:02",
    state: "Boundary kept",
  },
];

export const DRIFT_FIXTURE = {
  score: 84,
  checkedAt: "29 AUG 2026 · 10:12",
  signals: [
    { label: "Topic fit", value: 86, target: "at least 80", state: "on-course" },
    { label: "Source diversity", value: 73, target: "at least 70", state: "on-course" },
    { label: "Creator repetition", value: 18, target: "at most 15", state: "attention" },
    { label: "Outrage indicators", value: 3, target: "at most 5", state: "on-course" },
    { label: "Serendipity", value: 17, target: "exactly 20", state: "attention" },
  ],
};

export const MIGRATION_PREVIEW = {
  actions: [
    { action: "Follow reviewed creator matches", count: 4, mode: "Executable" },
    { action: "Preserve selected subscriptions", count: 7, mode: "Executable" },
    { action: "Compile native topic controls", count: 3, mode: "Guided" },
    { action: "Install portable exclusions", count: 2, mode: "Lab" },
  ],
  losses: [
    {
      severity: "Partial",
      title: "Personalized Home feed",
      detail: "The destination does not expose complete ranking control. Subscriptions can be preserved; Home cannot be certified.",
    },
    {
      severity: "Informational",
      title: "Serendipity target",
      detail: "Twenty percent remains a measurement target, not a directly writable destination setting.",
    },
  ],
};
